### ISSUE TITLE
Hebben we een dbc variabele?

### ISSUE THREAD

**Issue by beauterre** [MediacollegeAmsterdam/veilig_programmeren#36]
$password = mysqli_real_escape_string($dbc,trim($_POST['password']));

Kunnen we mysqli_real_escape_string ook anders doen?

LETOP: http://dev.mysql.com/doc/refman/5.1/en/news-5-1-11.html

**Comment by StefvanEgmond** [comment]
> LETOP: http://dev.mysql.com/doc/refman/5.1/en/news-5-1-11.html

Page not found lol

**Comment by beauterre** [comment]
Ah, goed gespot.. De link is niet langer valid. Ik weet zelf ook niet meer waarnaar ik verwees, maar iets over security..  Affijn, hier is de definitie:
https://dev.mysql.com/doc/refman/8.0/en/mysql-real-escape-string.html
(zolang die dus blijft bestaan)..
MySql-real-escape-string zorgt ervoor dat er een valide query string ontstaat, maar garandeert NIET dat de functionaliteit dan ook blijft bestaan.
Voor een hoop dingen is dit dus NIET functioneel en kan het verwarrende resultaten geven.
Als je hem gebruikt, dan alleen VLAK voordat je iets in een query stopt.

**Comment by beauterre** [comment]
Ik heb overigens Maartens Code even gefixed, omdat ik me kan voorstellen dat juist dit voorbeeld verwarrend is. Uiteindelijk moet het een referentie worden..

**Comment by theodenblanken** [comment]
Dag Hjalmar,

moet ik hieruit concluderen dat Stef alleen een probleem met GitHub heeft als ik hem les geef??

v.g. Theo

**Comment by beauterre** [comment]
Hij kan in ieder geval issues maken
